### ISSUE TITLE
reCaptcha Website Help

### ISSUE THREAD

**Issue by ProHyphonzDaCoder** [nates/ward#14]
So I went into the reCaptcha v2 Website and I followed all of you instructions but at the end it asked me for the public-key? But the website gave me a site key and a secret key. I was confused at that point what I should do. And it said if you are using a domain put it in the config.json but the website forces you to use a domain or else it wont create so please help me fix some errors. number 1 error - the public key and private key, number 2 - Should me domain be like name.com or something and my bot gives me a invalid site so please help!

**Comment by nates** [comment]
If you are hosting on your local computer set the domain to 127.0.0.1, if not use your domain. When I said public key, I meant site key.

**Comment by ProHyphonzDaCoder** [comment]
So Nate for the domain should it be like localhost:127.0.0.0? and for the config.json "domain": "localhost:127.0.0.1" should it be this?

**Comment by ProHyphonzDaCoder** [comment]
And Im Hosting The Bot on repl.it. So what do i do?

**Comment by nates** [comment]
It should be, "domain": "127.0.0.1", but if you are using repl.it, they will give you a domain to use (google: how to find repl.it project domain)

**Comment by ProHyphonzDaCoder** [comment]
im confused now can you dm me on discord? Discord is - Spike I AM TOY#1699

**Comment by ProHyphonzDaCoder** [comment]
@nates

**Comment by ProHyphonzDaCoder** [comment]
Mr Nates can you please help! I have a issue

**Comment by ProHyphonzDaCoder** [comment]
MR NATEEEEE REEEEEEEEEEEEEE. So Basically WTF DO I DO???. So I go to reCaptcha Website what should I put as my domain???

**Comment by ProHyphonzDaCoder** [comment]
IM CONFUSED BY YOUR TUTORIAL BRUH

**Comment by nates** [comment]
Put the domain as the repl.it domain

**Comment by ProHyphonzDaCoder** [comment]
so it needs to connect right?

**Comment by ProHyphonzDaCoder** [comment]
I got the repl.it domain. But it said enter your domain so I entered 127.0.0.1

**Comment by ProHyphonzDaCoder** [comment]
is that right?

**Comment by nates** [comment]
Do you know your repl.it domain?

**Comment by ProHyphonzDaCoder** [comment]
yes I just got it

**Comment by ProHyphonzDaCoder** [comment]
but I get an error

**Comment by nates** [comment]
Use that on recaptcha and the config

**Comment by ProHyphonzDaCoder** [comment]
when I open the website

**Comment by ProHyphonzDaCoder** [comment]
nates can you dm me on discord

**Comment by ProHyphonzDaCoder** [comment]
I am quite unclear

**Comment by ProHyphonzDaCoder** [comment]
nates???

**Comment by ProHyphonzDaCoder** [comment]
my guy left me lmao

**Comment by nates** [comment]
I sent you a friend request
