### ISSUE TITLE
Cannot read property 'g-recaptcha-response' of undefined

### ISSUE THREAD

**Issue by karlmendoza14** [nates/ward#17]
When ever i submit the captcha, this error shows up

> UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'g-recaptcha-response' of undefined
>     at C:\Users\Karl\Desktop\ward-master\server.js:34:123
>     at Layer.handle [as handle_request] (C:\Users\Karl\Desktop\ward-master\node_modules\express\lib\router\layer.js:95:5)
>     at next (C:\Users\Karl\Desktop\ward-master\node_modules\express\lib\router\route.js:137:13)
>     at Route.dispatch (C:\Users\Karl\Desktop\ward-master\node_modules\express\lib\router\route.js:112:3)
>     at Layer.handle [as handle_request] (C:\Users\Karl\Desktop\ward-master\node_modules\express\lib\router\layer.js:95:5)
>     at C:\Users\Karl\Desktop\ward-master\node_modules\express\lib\router\index.js:281:22
>     at param (C:\Users\Karl\Desktop\ward-master\node_modules\express\lib\router\index.js:354:14)
>     at param (C:\Users\Karl\Desktop\ward-master\node_modules\express\lib\router\index.js:365:14)
>     at Function.process_params (C:\Users\Karl\Desktop\ward-master\node_modules\express\lib\router\index.js:410:3)
>     at next (C:\Users\Karl\Desktop\ward-master\node_modules\express\lib\router\index.js:275:10)

Any fixes?

**Comment by nates** [comment]
Fixed in latest commit.
