### ISSUE TITLE
Config My Dns

### ISSUE THREAD

**Issue by Seyzou** [nates/ward#18]
Hey,
I can't configure my DNS access, do you have any idea how to do it? 
I added in my config: verif.mayeda.ga (the domain) and in my dns access the ip address of the hosting of my bot to the domain is it good?
Thanks in advance !

**Comment by nates** [comment]
This would be the correct DNS.

**Comment by nates** [comment]
Closing this, reopen if you need more help.

**Comment by Seyzou** [comment]
I'm sorry, but when I configure my dns, it returns 404 with the url verif.mayeda.ga/verif/<code>. Could you help me

**Comment by nates** [comment]
It will return 404 until you get sent a link when you join the server.

**Comment by Seyzou** [comment]
my url verif.mayeda.ga works but once the code is added it returns 404 :/

**Comment by Seyzou** [comment]
you should make a tuto for people who do not use it in localhost

**Comment by nates** [comment]
its should be verify btw

**Comment by Seyzou** [comment]
yes, I did everything right but adapted to my bot (which does not change anything because in localhost it works)
What you need to know is that my bot is hosted at home for now (I'm buying a vps tomorrow) and my site is on a plesk access. 
In my config.js I put my domain mayeda.ga so in the embed it says https://mayeda.ga/verify/<code> but when I click on it the site sends me back my 404 page. When I change my url to localhost/verify/code it works. So I think that the server and the site must be hosted on the same machine for your code to work, or I'm wrong.
But if you would have a solution because I'm really not very good for anything related to the website

**Comment by nates** [comment]
Correct, the site and bot must be on the same server. Only one machine is needed.
