### ISSUE TITLE
Feature Request for passing secrets via environmental variables

### ISSUE THREAD

**Issue by felixsam359** [nates/ward#19]
In version 1 of your bot secrets were passed by a file named as `variables.js`. So it was easy for us to change each variable into `process.env.variablesecret`. But now version 2 uses `json` to pass secrets. So it's little bit pain to search through the JavaScript files and change the required things to environmental variables. I managed to do so and the bot is working very well. 

I came across this repo yesterday https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#environment-variables 

[Config.js](https://github.com/Dragory/modmailbot/blob/master/src/cfg.js)
```
// Load config values from environment variables
const envKeyPrefix = "MM_";
let loadedEnvValues = 0;

for (const [key, value] of Object.entries(process.env)) {
  if (! key.startsWith(envKeyPrefix)) continue;

  
  
  const configKey = key.slice(envKeyPrefix.length)
    .toLowerCase()
    .replace(/([a-z])_([a-z])/g, (m, m1, m2) => `${m1}${m2.toUpperCase()}`)
    .replace("__", ".");

  config[configKey] = value.includes("||")
    ? value.split("||")
    : value;

  loadedEnvValues++;
}
```
This repo uses `config.ini` to pass secrets and at same time secrets can be passed by adding a predefined prefix and changing the variables names into snake case.

So in near future can you please add a feature so that it's easy for us to pass secrets via environmental variables. 

Thank you for making a very beautiful bot.

**Comment by nates** [comment]
I will look into this! Thanks for the support.

**Comment by nates** [comment]
I've added support for repl.it, if you must, you can change it to work with your workspace.

**Comment by felixsam359** [comment]
[![Run on Repl.it](https://repl.it/badge/github/nates/ward)](https://repl.it/@nates3/ward)
 
Thanks for your quick response. I really appreciate it. Keep up good work. And I added a badge for your repl. You can add on your readme.md it make it for beautiful.

**Comment by nates** [comment]
Thank you, I have added this to the readme
