### ISSUE TITLE
how to add arc

### ISSUE THREAD

**Issue by crimerip** [nates/ward#21]
how do i add arc when i try to add arc's arc-sw.js in the root directory where the config.json file is located arc cant find it and i cant.

**Comment by nates** [comment]
I'm not sure what arc is

**Comment by nates** [comment]
I'm closing this, reply if you need more help.

**Comment by kittylegitcheck2** [comment]
Hey, arc is arc.io they wanna earn a few dollars by verifying people.

**Comment by kittylegitcheck2** [comment]
Just saying sorry if this will botter you

**Comment by nates** [comment]
I am not going to help add arc.

**Comment by rodrigoricky** [comment]
@Dominiqos @1800s  This is late, but if you still need this, I can help.

If you already have arc account, just create a file inside the `assets` folder, name it `arc-sw.js` then copy inside this [website](https://arc.io/arc-sw.js) then in each HTML file before `</head>` add the widget code. Here's an example.

```js
<head>
    <script async src="https://arc.io/widget.min.js#g44qJMir"></script>
    ...
</head>
```

**Comment by Dominiqos** [comment]
Thanks for responding! I still use your thing so this is very useful for me!

pon., 27 gru 2021, 08:20 użytkownik rodrigoricky ***@***.***>
napisał:

**Comment by rodrigoricky** [comment]
No problem, love to help people (p.s I don't exactly own this repo soo yeah 😅)
