### ISSUE TITLE
Command for resending verification

### ISSUE THREAD

**Issue by Dominiqos** [nates/ward#22]
Hey, i have a great idea for the bot. Add a command for resending the captcha link. It would be useful because some people do not look at their dms after joining servers.

**Comment by kittylegitcheck2** [comment]
Also while i am at it, is ot possible for the page not to be tagged as dangerous? It makes 9 out of each 50 people leave

**Comment by nates** [comment]
> 
> 
> Hey, i have a great idea for the bot. Add a command for resending the captcha link. It would be useful because some people do not look at their dms after joining servers.

Great idea, I will think about adding this.



> 
> 
> Also while i am at it, is ot possible for the page not to be tagged as dangerous? It makes 3 out of each 100 people leave

It is possible, you must setup the https mode with an ssl certificate. You can generate some with Let's Encrypt.

**Comment by kittylegitcheck2** [comment]
Holy shit, i did not expect a response

**Comment by nates** [comment]
You can google how to generate an SSL certificate with Let's Encrypt and you should find a way to do it, if not just message back.

**Comment by nates** [comment]
I am adding these labels if anyone would be interested in opening a pull request,

**Comment by FatGrizzly** [comment]
> Also while i am at it, is ot possible for the page not to be tagged as dangerous? It makes 3 out of each 100 people leave

it might be your domain tho, it might be flagged by google

run a test here
https://transparencyreport.google.com/safe-browsing/search?url=yourdomain.name

**Comment by snaildos** [comment]
Good late afternoon. I added tihs inspite of my big fat PR!
#27 
Hope you all enjoy! :)

**Comment by FatGrizzly** [comment]
yo snaildos, nice meeting you here

**Comment by FatGrizzly** [comment]
thanks for pr :)
