### ISSUE TITLE
Need some help setting up

### ISSUE THREAD

**Issue by official-dbrown** [nates/ward#26]
Hey I think I mucked up the setup cause it says

ERROR for site owner:
Invalid domain for site key

But the key I put in is correct.

And than on replit it says Cannot GET /

**Comment by nates** [comment]
It will say Cannot GET / on replit, but you may be using the incorrect site key. Check on your reCAPTCHA dashboard to make sure you are using the right keys.

**Comment by official-dbrown** [comment]
Its all correct, I added you on discord

**Comment by nates** [comment]
Ok
